/// Flutter icons MyFlutterApp
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
library icons;

import 'package:flutter/widgets.dart';

class ImgurIcons {
  //ImgurIcons._();

  static const _kFontFam = 'imgurIcons';

  static const IconData heart = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData heart_broken = const IconData(0xf028, fontFamily: _kFontFam);
  static const IconData thumbs_up_alt = const IconData(0xf164, fontFamily: _kFontFam);
  static const IconData thumbs_down_alt = const IconData(0xf165, fontFamily: _kFontFam);
  static const IconData commenting = const IconData(0xf27a, fontFamily: _kFontFam);
}
