##
## EPITECH PROJECT, 2018
## sec
## File description:
## sec
##

all:
	@cp ex01/hex_to_base64.py challenge01
	@cp ex02/fixed_xor.py challenge02
	@cp ex03/single_xor.py challenge03
	@cp ex04/detected_single_xor.py challenge04
	@cp ex05/repeating_key.py challenge05
	@cp ex06/break_rk.py challenge06
	@cp ex07/aes_in_ecb.py challenge07
	@cp ex08/Detect_AES.py challenge08
	@cp ex09/implement.py challenge09
	@cp ex10/byte_at_a_time.py challenge10
	@cp ex11/cut_and_paste.py challenge11
	@cp ex12/harder.py challenge12
	@cp ex13/bitflipping.py challenge13
	@cp ex14/oracle.py challenge14
clean:
	@rm challenge*
